### ISSUE TITLE
Unable to run build process

### ISSUE THREAD

**Issue by rajeevriitm** [ksachdeva/angular2-swing#28]
I am trying run  ``npm run build`` but I get this error.

```
Error at /home/raj/ionic/angular2-swing/node_modules/@angular/core/src/di/reflective_provider.d.ts:87:123: Cannot find name 'Map'.
Error at /home/raj/ionic/angular2-swing/node_modules/@angular/core/src/di/reflective_provider.d.ts:87:165: Cannot find name 'Map'.
Error at /home/raj/ionic/angular2-swing/node_modules/rxjs/Observable.d.ts:69:60: 'Promise' only refers to a type, but is being used as a value here.
Error at /home/raj/ionic/angular2-swing/node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts:15:48: Cannot find name 'Iterable'.
Error at /home/raj/ionic/angular2-swing/node_modules/@angular/core/src/change_detection/differs/keyvalue_differs.d.ts:23:18: Cannot find name 'Map'.
Error at /home/raj/ionic/angular2-swing/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:24:16: Cannot find name 'Map'.
Error at /home/raj/ionic/angular2-swing/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:32:16: Cannot find name 'Map'.
Error at /home/raj/ionic/angular2-swing/node_modules/@angular/common/src/directives/ng_class.d.ts:48:34: Cannot find name 'Set'.
```

Any idea why? I am working on an update to enable `prepend` option for cards in the stack .

**Comment by mashhoodr** [comment]
@rajeevriitm there is a PR for prepend already open, you can check it out.

I think this error relates to @types being missing. Which version of node/npm are you using?

**Comment by rajeevriitm** [comment]
I have the latest version. npm - `4.5.0` and node `7.9.0` . Ya the error comes from type missing, i tried adding core.js types but more errors.

I looked at the PR. Thats what I was working for as well. But I think `prepend`  should be optional and pass default value `false`

**Comment by mashhoodr** [comment]
@rajeevriitm we can close this now?

**Comment by rajeevriitm** [comment]
Ya . fixed it by adding types.
