### ISSUE TITLE
Cannot read property 'DOWN' of undefined

### ISSUE THREAD

**Issue by colouredFunk** [ksachdeva/angular2-swing#35]
I've just installed this in Angular 4 but I'm getting the following error - 

TypeError: Cannot read property 'DOWN' of undefined
    at exports.Direction.exports.Direction (http://localhost:8100/build/vendor.js:120021:50)
    at Object.defineProperty.value (http://localhost:8100/build/vendor.js:120026:3)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:116894:15)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.217 (http://localhost:8100/build/main.js:241:74)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.198 (http://localhost:8100/build/main.js:212:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)

**Comment by airstep** [comment]
+1

**Comment by mashhoodr** [comment]
Sorry, going a bit busy, will have a look at this in the coming weekend.

**Comment by dfxe** [comment]
> +1

**Comment by isdanni** [comment]
+1

Wonder if this is solved?
